"""Run from backend: python -m scripts.seed_coverage [--export-sql PATH]."""

import argparse
import asyncio
from pathlib import Path

from sqlalchemy import select, text
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import insert

from app.models import Base, User
from app.security import hash_password
from scripts.coverage_data import TABLES, USERS


def datasets():
    yield from TABLES
    yield User, [
        {**{k: v for k, v in user.items() if k != "password"},
         "hashed_password": hash_password(user["password"])}
        for user in USERS
    ], "username"


async def seed(connection):
    """Insert missing fixtures atomically; never reset records edited by the user."""
    await connection.run_sync(Base.metadata.create_all)
    for model, rows, identity in datasets():
        table = model.__table__
        # Serialize fixture imports and prevent INSERTs from racing sequence adjustment.
        await connection.execute(text(f'LOCK TABLE "{table.name}" IN SHARE ROW EXCLUSIVE MODE'))
        existing = (await connection.execute(
            select(table.c.id, table.c[identity]).where(table.c.id.in_([r["id"] for r in rows]))
        )).all()
        expected = {r["id"]: r[identity] for r in rows}
        if any(expected[row[0]] != row[1] for row in existing):
            raise ValueError(f"Seed ID collision in {table.name}; existing data was not replaced.")
        await connection.execute(insert(table).values(rows).on_conflict_do_nothing(index_elements=[table.c.id]))
        # Explicit fixture IDs must not make subsequent API creates collide with existing rows.
        sequence = await connection.scalar(text("SELECT pg_get_serial_sequence(:table, 'id')"), {"table": table.name})
        if sequence:
            await connection.execute(text(
                f"SELECT setval(CAST(:sequence AS regclass), "
                f"GREATEST((SELECT MAX(id) FROM {table.name}), "
                f"pg_sequence_last_value(CAST(:sequence AS regclass)), 1), true)"
            ), {"sequence": sequence})


def export_sql(path):
    """Standalone PostgreSQL data script; tables must already exist from the current ORM."""
    chunks = [
        "-- Generated by python -m scripts.seed_coverage --export-sql ../db/sql/seed_coverage.sql",
        "-- Synthetic local/demo fixtures. Current ORM schema required (service_report, users).",
        "-- Existing fixture rows are preserved; ID collisions abort. Demo passwords: db/SEED_COVERAGE.md.",
        "\\set ON_ERROR_STOP on", "BEGIN;",
    ]
    for model, rows, identity in datasets():
        table = model.__table__
        chunks.append(f"LOCK TABLE {table.name} IN SHARE ROW EXCLUSIVE MODE;")
        identities = []
        for row in rows:
            value = row[identity].replace("'", "''")
            identities.append(f"({row['id']}, '{value}')")
        chunks.append(
            f"DO $$ BEGIN IF EXISTS (SELECT 1 FROM {table.name} t JOIN (VALUES\n"
            + ",\n".join(identities)
            + f") AS expected(id, identity) ON expected.id = t.id WHERE t.{identity} <> expected.identity) "
            + f"THEN RAISE EXCEPTION 'Seed ID collision in {table.name}'; END IF; END $$;"
        )
        statement = insert(table).values(rows).on_conflict_do_nothing(index_elements=[table.c.id])
        compiled = str(statement.compile(dialect=postgresql.dialect(), compile_kwargs={"literal_binds": True}))
        chunks.append(compiled.replace(" VALUES (", " VALUES\n    (").replace("), (", "),\n    (") + ";")
        chunks.append(
            f"SELECT setval(pg_get_serial_sequence('{table.name}', 'id'), "
            f"GREATEST((SELECT MAX(id) FROM {table.name}), "
            f"pg_sequence_last_value(pg_get_serial_sequence('{table.name}', 'id')::regclass), 1), true);"
        )
    chunks.append("COMMIT;\n")
    Path(path).write_text("\n\n".join(chunks), encoding="utf-8")
    print(f"Exported {path}")


async def main():
    from app.database import engine

    engine.echo = False
    try:
        async with engine.begin() as connection:
            await seed(connection)
        counts = [f"{len(rows)} {model.__tablename__}" for model, rows, _ in TABLES]
        counts.append(f"{len(USERS)} users")
        print("Seed ready: " + ", ".join(counts) + ".")
        print("Existing fixture rows preserved. See db/SEED_COVERAGE.md for credentials and expected results.")
    finally:
        await engine.dispose()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--export-sql", metavar="PATH", help="Export SQL without connecting to the database")
    args = parser.parse_args()
    if args.export_sql:
        export_sql(args.export_sql)
    else:
        asyncio.run(main())
