import os 
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine


DATABASE_URL = os.environ.get(
    "DATABASE_URL",
    "postgresql+asyncpg://postgres:postgres@localhost:5432/medflow_dev"

)
#echo = True enables the logging of all SQL statements generated by SQLAlchemy
engine = create_async_engine(DATABASE_URL, echo = True)


#xpire_on_commit = False prevents the session frm expiring object after a commit
AsyncSessionLocal = async_sessionmaker(engine, expire_on_commit = False)