-- Generated by python -m scripts.seed_coverage --export-sql ../db/sql/seed_coverage.sql

-- Synthetic local/demo fixtures. Current ORM schema required (service_report, users).

-- Existing fixture rows are preserved; ID collisions abort. Demo passwords: db/SEED_COVERAGE.md.

\set ON_ERROR_STOP on

BEGIN;

LOCK TABLE hospitals IN SHARE ROW EXCLUSIVE MODE;

DO $$ BEGIN IF EXISTS (SELECT 1 FROM hospitals t JOIN (VALUES
(9101, 'Seed Tampa Central'),
(9102, 'Seed Orlando Regional'),
(9103, 'Seed Boston Medical')) AS expected(id, identity) ON expected.id = t.id WHERE t.name <> expected.identity) THEN RAISE EXCEPTION 'Seed ID collision in hospitals'; END IF; END $$;

INSERT INTO hospitals (id, name, location_region, capacity, supervisor_id) VALUES
    (9101, 'Seed Tampa Central', 'US-Southeast', 1200, 9901),
    (9102, 'Seed Orlando Regional', 'US-Southeast', 650, 9901),
    (9103, 'Seed Boston Medical', 'US-Northeast', 900, 9902) ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('hospitals', 'id'), GREATEST((SELECT MAX(id) FROM hospitals), pg_sequence_last_value(pg_get_serial_sequence('hospitals', 'id')::regclass), 1), true);

LOCK TABLE technicians IN SHARE ROW EXCLUSIVE MODE;

DO $$ BEGIN IF EXISTS (SELECT 1 FROM technicians t JOIN (VALUES
(9201, 'Seed Alice Chen'),
(9202, 'Seed Sofia Rivera'),
(9203, 'Seed Priya Shah')) AS expected(id, identity) ON expected.id = t.id WHERE t.name <> expected.identity) THEN RAISE EXCEPTION 'Seed ID collision in technicians'; END IF; END $$;

INSERT INTO technicians (id, name, hospital_id) VALUES
    (9201, 'Seed Alice Chen', 9101),
    (9202, 'Seed Sofia Rivera', 9102),
    (9203, 'Seed Priya Shah', 9103) ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('technicians', 'id'), GREATEST((SELECT MAX(id) FROM technicians), pg_sequence_last_value(pg_get_serial_sequence('technicians', 'id')::regclass), 1), true);

LOCK TABLE equipments IN SHARE ROW EXCLUSIVE MODE;

DO $$ BEGIN IF EXISTS (SELECT 1 FROM equipments t JOIN (VALUES
(9301, 'SEED-MF-9301'),
(9302, 'SEED-MF-9302'),
(9303, 'SEED-MF-9303'),
(9304, 'SEED-MF-9304'),
(9305, 'SEED-MF-9305'),
(9306, 'SEED-MF-9306'),
(9307, 'SEED-MF-9307'),
(9308, 'SEED-MF-9308')) AS expected(id, identity) ON expected.id = t.id WHERE t.serial_number <> expected.identity) THEN RAISE EXCEPTION 'Seed ID collision in equipments'; END IF; END $$;

INSERT INTO equipments (id, serial_number, model, status, charge_level, hospital_id) VALUES
    (9301, 'SEED-MF-9301', 'Seed Ventilator', 'Available', 10, 9101),
    (9302, 'SEED-MF-9302', 'Seed Infusion Pump', 'In-Use', 20, 9101),
    (9303, 'SEED-MF-9303', 'Seed Patient Monitor', 'Maintenance', 80, 9101),
    (9304, 'SEED-MF-9304', 'Seed Mobile Imaging Cart', 'Offline', 5, 9101),
    (9305, 'SEED-MF-9305', 'Seed Ventilator', 'Available', 70, 9102),
    (9306, 'SEED-MF-9306', 'Seed Infusion Pump', 'Maintenance', 15, 9102),
    (9307, 'SEED-MF-9307', 'Seed Patient Monitor', 'Available', 50, 9102),
    (9308, 'SEED-MF-9308', 'Seed Ventilator', 'Available', 100, 9103) ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('equipments', 'id'), GREATEST((SELECT MAX(id) FROM equipments), pg_sequence_last_value(pg_get_serial_sequence('equipments', 'id')::regclass), 1), true);

LOCK TABLE work_orders IN SHARE ROW EXCLUSIVE MODE;

DO $$ BEGIN IF EXISTS (SELECT 1 FROM work_orders t JOIN (VALUES
(9401, 'Seed low pending cross-site inspection'),
(9402, 'Seed medium in-progress cross-site inspection'),
(9403, 'Seed critical completed same-site inspection'),
(9404, 'Seed critical failed same-site inspection'),
(9405, 'Seed critical completed cross-site inspection'),
(9406, 'Seed medium failed same-site inspection')) AS expected(id, identity) ON expected.id = t.id WHERE t.title <> expected.identity) THEN RAISE EXCEPTION 'Seed ID collision in work_orders'; END IF; END $$;

INSERT INTO work_orders (id, title, priority, status, equipment_id, technician_id) VALUES
    (9401, 'Seed low pending cross-site inspection', 'Low', 'Pending', 9301, 9202),
    (9402, 'Seed medium in-progress cross-site inspection', 'Medium', 'In-Progress', 9305, 9201),
    (9403, 'Seed critical completed same-site inspection', 'Critical', 'Completed', 9301, 9201),
    (9404, 'Seed critical failed same-site inspection', 'Critical', 'Failed', 9305, 9202),
    (9405, 'Seed critical completed cross-site inspection', 'Critical', 'Completed', 9302, 9202),
    (9406, 'Seed medium failed same-site inspection', 'Medium', 'Failed', 9306, 9202) ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('work_orders', 'id'), GREATEST((SELECT MAX(id) FROM work_orders), pg_sequence_last_value(pg_get_serial_sequence('work_orders', 'id')::regclass), 1), true);

LOCK TABLE service_report IN SHARE ROW EXCLUSIVE MODE;

DO $$ BEGIN IF EXISTS (SELECT 1 FROM service_report t JOIN (VALUES
(9601, 'https://reports.medflow.example/seed/9403/9601.pdf'),
(9602, 'https://reports.medflow.example/seed/9404/9602.txt'),
(9603, 'https://reports.medflow.example/seed/9405/9603.png')) AS expected(id, identity) ON expected.id = t.id WHERE t.file_url <> expected.identity) THEN RAISE EXCEPTION 'Seed ID collision in service_report'; END IF; END $$;

INSERT INTO service_report (id, work_order_id, file_url, notes, created_at) VALUES
    (9601, 9403, 'https://reports.medflow.example/seed/9403/9601.pdf', 'Completed inspection', '2026-08-20 09:30:00'),
    (9602, 9404, 'https://reports.medflow.example/seed/9404/9602.txt', NULL, '2026-08-20 10:30:00'),
    (9603, 9405, 'https://reports.medflow.example/seed/9405/9603.png', 'Inspection image', '2026-08-20 11:30:00') ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('service_report', 'id'), GREATEST((SELECT MAX(id) FROM service_report), pg_sequence_last_value(pg_get_serial_sequence('service_report', 'id')::regclass), 1), true);

LOCK TABLE users IN SHARE ROW EXCLUSIVE MODE;

DO $$ BEGIN IF EXISTS (SELECT 1 FROM users t JOIN (VALUES
(9501, 'seed_admin'),
(9502, 'seed_technician'),
(9503, 'seed_auditor')) AS expected(id, identity) ON expected.id = t.id WHERE t.username <> expected.identity) THEN RAISE EXCEPTION 'Seed ID collision in users'; END IF; END $$;

INSERT INTO users (id, username, hashed_password, role, is_active, technician_id) VALUES
    (9501, 'seed_admin', '$2b$12$RiAYM67jYie2RQMKEnRpqeQ/J/uLkW9xBTIBsHcQE5eoN6hnoqOfK', 'Clinical Admin', true, NULL),
    (9502, 'seed_technician', '$2b$12$gKowTGn8KUHatjIKEpQQT.biGy/S37W8b/HXghEkVbxa08wXDgN1a', 'Field Technician', true, 9201),
    (9503, 'seed_auditor', '$2b$12$EBDLi.3ioH7kGAyh3Rni7ujBL/6fxYq9QtioqKLgtOdmy/fD5rIGi', 'Auditor', true, NULL) ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('users', 'id'), GREATEST((SELECT MAX(id) FROM users), pg_sequence_last_value(pg_get_serial_sequence('users', 'id')::regclass), 1), true);

COMMIT;
